# Schema for the configuration files of the Lambda Form.

lambda_form.settings:
  type: config_object
  label: 'Lambda Form Settings'
  mapping:
    endpoint:
      type: uri
      label: 'The lambda endpoint URL'
